Host: "localhost"
Port: 3306
Database: "Market"
Username: "root"
Password: ""



Message.NoPermission: "&8[&bWanted&8] &fJe hebt geen permissie tot deze command."
Message.EmptyList: "&8[&bWanted&8] &f Er zijn geen spelers die wanted zijn."
Message.EventmodusAan: "&8[&bWanted&8] &f De eventmodus is aangezet, het wantedsysteem zal nu niet werken."
Message.EventmodusUit: "&8[&bWanted&8] &f De eventmodus is uitgezet, het wantedsysteem zal nu werken."
Message.PlayerOffline: "&8[&bWanted&8] &f Deze speler is offline."
Message.SuccesRemove: "&8[&bWanted&8] &f De speler is succesvol verwijdert uit de wantedlijst."
Message.PlayerNotWanted: "&8[&bWanted&8] &f Deze speler is niet wanted."
Message.NotNegative: "&8[&bWanted&8] &f Het getal mag niet negatief zijn of boven de 20."
Message.LevelNeedNumber: "&8[&bWanted&8] &f You can't set a player wanted with letters"
Message.WantedEnd: "&8[&bWanted&8] &f Je bent niet meer wanted, maar pasop, log niet uit als je in een gevaarlijke situatie zit."


FirstKill: 9
SecondKill: 15
ThirdKill: 20